swagger: "2.0"

info:
  title: Backup Microservice
  version: "0.1"
  description: BACKUP Microservice

consumes:
  - application/json

produces:
  - application/json

basePath: "/api/backup"

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer
    x-bearerInfoFunc: app.decode_token

paths:
  /categories/{user_id}:
    get:
      tags: [Backup]
      operationId: app.categories
      parameters:
        - $ref: "#/parameters/user_id"
      responses:
        200:
          description: Return categories data for user
        404:
          description: Not found

  /accounts/{user_id}:
    get:
      tags: [Backup]
      operationId: app.accounts
      parameters:
        - $ref: "#/parameters/user_id"
      responses:
        200:
          description: Return accounts data for user
        404:
          description: Not found

  /transactions/{user_id}:
    get:
      tags: [Backup]
      operationId: app.transactions
      parameters:
        - $ref: "#/parameters/user_id"
      responses:
        200:
          description: Return transactions data for user
        404:
          description: Not found

  /backup/{user_id}:
    get:
      tags: [Backup]
      operationId: app.all
      parameters:
        - $ref: "#/parameters/user_id"
      responses:
        200:
          description: Return backup file location for user
        404:
          description: Not found

parameters:
  user_id:
    name: user_id
    description: User unique id
    in: path
    type: integer
    required: true
